# Generated by Django 3.1.7 on 2021-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectionData', '0002_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='elections',
            name='Senates',
            field=models.IntegerField(default=0),
        ),
    ]
